### PR TITLE
Separate `it` and `gatling-it` configurations 

### PR DESCRIPTION
**Pull request by teliatko**
Fixes gatling/gatling#3162

### CODE REVIEW

**Comment by slandelle** [comment]
LGTM. @notdryft could you please approve?

**Comment by slandelle** [comment]
Thanks a lot!

**Comment by teliatko** [comment]
Btw. what is the versioning schema of `gatling-sbt` plugin? It is different as `gatling`? I'm asking only because `gatling` is in 2.2.2 alreeady, but SBT plugin is not.

**Comment by slandelle** [comment]
For plugins (maven too), we use the same major and minor versions, but not the same fix.

**Pull request merged**
