### PR TITLE
support sbt 1.0

### PR DESCRIPTION
**Pull request by xuwei-k**
https://github.com/gatling/gatling/issues/3344

### CODE REVIEW

**Comment by slandelle** [comment]
Thanks a lot! I'll be afk for the next 2 weeks, I'll test and merge when I'll be back. Sorry for the delay.

**Comment by slandelle** [comment]
@xuwei-k How is one supposed to cross publish a sbt plugin? `+publish` only published the 0.13 version: https://bintray.com/gatling/sbt-plugins/gatling-sbt/2.2.2#files/io.gatling%2Fgatling-sbt%2Fscala_2.10

Also, should Scala be upgraded to 2.11 or 2.12?

**Comment by xuwei-k** [comment]
You should use `^ publish` instead of `+ publish`.
see http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#sbt-cross-building

**Comment by slandelle** [comment]
Thanks!
LGTM now: https://bintray.com/gatling/sbt-plugins/gatling-sbt#files/io.gatling%2Fgatling-sbt%2Fscala_2.12%2Fsbt_1.0%2F2.2.2

**Pull request merged**
